export const CART_ADD_REQUEST=" CART_ADD_REQUEST"
export const CART_ADD_ITEM=" CART_ADD_ITEM"
export const CART_ADD_FAIL=" CART_ADD_FAIL"

export const CART_REMOVE_REQUEST=" CART_REMOVE_REQUEST"
export const CART_REMOVE_ITEM=" CART_REMOVE_ITEM"
export const CART_REMOVE_FAIL=" CART_REMOVE_FAIL"

export const ORDER_ADD_REQUEST=" ORDERADD_REQUEST"
export const ORDER_ADD_ITEM=" ORDER_ADD_ITEM"
export const ORDER_ADD_FAIL="ORDER_ADD_FAIL"

export const SHIPPINGORDER_ADD_REQUEST=" SHIPPINGORDERADD_REQUEST"
export const SHIPPINGORDER_ADD_ITEM=" SHIPPINGORDER_ADD_ITEM"
export const SHIPPINGORDER_ADD_FAIL="SHIPPINGORDER_ADD_FAIL"

export const ORDERITEM_ADD_REQUEST="ORDERITEM_ADD_REQUEST"
export const ORDERITEM_ADD_ITEM="ORDERITEM_ADD_ITEM"
export const ORDERITEM_ADD_FAIL="ORDERITEM_ADD_FAIL"